---
- hosts: all
  remote_user: pi
  tasks:
  - name: Add SSH key
    authorized_key:
      user: pi
      state: present
      key: "{{ lookup('file', '/home/pi/.ssh/id_rsa.pub') }}"
  - name: Check root filesystem
    assert:
      that: 
        - not {{ item.mount == '/' and ( item.size_total < 4000000000 ) }}
    with_items: "{{ ansible_mounts }}"
    ignore_errors: yes
    register: small_root
  - name: Expand root filesystem
    become: true
    command: "raspi-config --expand-rootfs"
    when: small_root|failed
