---
- hosts: all
  remote_user: pi
  tasks:

  - name: Check presence of Docker
    systemd:
      state: started
      name: docker
    ignore_errors: yes
    register: docker_service

  - name: Install Docker
    command: "bash -c 'curl -sSL https://get.docker.com | sh'"
    when: docker_service|failed

  - name: Add user to docker group
    become: true
    user:
      name: pi
      groups: docker

  - name: Add service names
    become: true
    blockinfile:
      dest: /etc/hosts
      marker: "# {mark} ANSIBLE MANAGED HOSTNAMES"
      content: |
        172.19.181.254 docker-registry

# Create custom Docker config file
  - become: true
    block:
      - copy:
          dest: /etc/systemd/system
          src: /lib/systemd/system/docker.service
          remote_src: true
          force: false
      - replace:
          dest: /etc/systemd/system/docker.service
          regexp: 'ExecStart=.*$'
          replace: 'ExecStart=/usr/bin/dockerd -H fd:// --registry-mirror=http://docker-registry:5000'
      - systemd:
          state: restarted
          daemon_reload: yes
          name: docker
